language: android

jdk:
  - oraclejdk8

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 30
  - adb devices

android:
  components:
    - tools
    - build-tools-26.0.0
    - android-24
    - platform-tools

    - extra-android-m2repository

    # Emulator - Use older android emulator to make Spoon use internal storage
    - sys-img-armeabi-v7a-android-19

notifications:
  email: false